[tool.poetry]
name = "travel-agent"
version = "0.1.0"
description = ""
authors = ["Vinicius Abreu <vabreu@testreach.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
